hcl/ast/ast_test.go
hcl/ast/walk.go
hcl/printer/nodes.go
json/parser/flatten.go

With the Walk function it's not easy to rewrite the node as we don't
have any kind of reference to the parent. If we want to rewrite a given
AST, we have to manually traverse it as Walk is not usable.
The new Rewrite function enables us to rewrite the AST easily by
returning the modified node for each traversed node. This idea was also
talked here:
https://groups.google.com/forum/#!topic/golang-nuts/cRZQV36IckM
extensively.

ast: add Rewrite() to rewrite AST

---

hcl/parser/error.go
hcl/parser/error_test.go
hcl/parser/parser.go

Fixes #54 
This introduces a special error struct so that the position is available on every parse error.

hcl/parser: store position on every parse err [GH-54]

---

README.md

Makes understanding the consumable API much simpler rather than digging through source code.

Adding Godoc link

---

decoder_test.go
hcl/parser/test-fixtures/complex.hcl
hcl/scanner/scanner_test.go
hcl/strconv/quote.go
hcl/strconv/quote_test.go
hcl/token/token_test.go
json/scanner/scanner_test.go
test-fixtures/interpolate_escape.hcl

Before the parser rewrite, HCL would silently convert `\"` within
interpolation braces to `"`.
After the conversion, this became a syntax error.
We've found several instances of Terraform configs in the wild using
this syntax. It results in a hard "syntax error" message during config
parsing. While avoiding the extra escape on double quotes within
interpolations is definitely preferred, the UX of the syntax error feels
harsh enough to be worth inserting this backwards compatibility for now,
leaving us the option of deprecating it with a warning down the line.

Restore old behavior for \" within interpolations

---

hcl/strconv/quote.go
hcl/strconv/quote_test.go

A user testing an RC release of Terraform 0.6.7 found the following
string unexpectedly caused a syntax error:
"echo ${var.region}${element(split(",",var.zones),0)}"
This fixes the error and covers it with a test.

Handle multiple interpolations in string.

---

decoder_test.go
hcl/scanner/scanner.go
test-fixtures/tfvars.hcl

This is used in `.tfvars` files for Terraform in order to allow overriding values in maps, for example:
```hcl
map.key1 = "Value"
map.key2 = "OtherValue"
```
Not sure this is quite enough to fix the issues reported in 0.6.7 of Terraform, but it moves us past the parsing error.

Fix scanning of identifiers of the form 'map.key'

---

hcl/parser/parser.go
hcl/parser/parser_test.go

This fixes a regression in Terraform where HEREDOCS were previously supported in lists, reported in hashicorp/terraform#4065.

Support HEREDOCs in lists

---

hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

I think this should be enough to fix hashicorp/terraform#4069, though this is not yet verified and changes to the parser may also be necessary.

Fix scanner for Windows line endings and add tests

---

.gitignore
decoder.go
decoder_test.go

decoded structs may now use the ast.Node type to save the raw ast.Node; conceptually similar to how json.RawMessage works and is useful in situations where you would like to either (a) defer decoding or (b) require additional meta-data like #Pos

adds facility for deferred Decode similar to how json.RawMessage enables deferred Unmarshal

---

decoder.go

Several of the esoteric syntax errors we encounter in Terraform have
bubbled up errors from the decoder. Since all these errors have a Node
in context, they can report their position which makes them _much_ more
helpful to the user, even if the error message itself is confusing.
I tried to move around PosError somewhere but got stuck finding a good
spot for it that doesn't have either a silly name or an import cycle, so
for now I'm just cross referencing into the parser package to reference
the error type.

add position to all decoder errors

---

hcl/fmtcmd/fmtcmd.go
hcl/fmtcmd/fmtcmd_test.go
hcl/fmtcmd/test-fixtures/.hidden.ignore
hcl/fmtcmd/test-fixtures/file.ignore

This uses the `printer` package to normalise HCL files. It's inspired by
github.com/fatih/hclfmt - but it differs in that it's intended to be more
generic, re-usable, and follow the semantics of `gofmt` or `go fmt`.
I intend to utilise this in Terraform by implementing `terraform fmt`
sub-command which will normalise all files in the current working directory
(like `go fmt ./..`) or contents over STDIN (with `terraform fmt -` that
could be used by editor plugins). So that Terraform users can benefit from
linting without installing another package/binary.
I hope that by placing most of the logic in the HCL package it should be
easy to implement sub-commands in other projects that also use HCL.
Some notes about the implementation:
- the significant difference from `gofmt` is that …

Add new fmtcmd package (linting)

---

decoder.go
decoder_test.go

Fixes GH-60
/cc @jen20 @mitchellh

Ensure top-level object literals are arrays

---

decoder.go
decoder_test.go
lex.go
lex_test.go
parse.go

The std encoding format is Unmarshal([]byte, interface{}) error.
This naturally lends itself well to being passed readfile or exhausted
reader/buffer.
- Closes #4 
- Closes #92 
- Fixes #20 
This is just a rebase of 92 with authorship maintained

Add encoding API functions

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/empty_block.golden
hcl/printer/testdata/empty_block.input

This is to match the same criteria as in gofmt.
Fixes #94
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>

printer: don't write a newline on empty objects

---

appveyor.yml
decoder_test.go
hcl/fmtcmd/fmtcmd_test.go
testhelper/unix2dos.go

This is necessary because of the effects of autocrlf on Windows.

Fix scanner tests on Windows

---

decoder.go
decoder_test.go
test-fixtures/nested_provider_bad.hcl

This now gives an error instead of a panic when encountering configuration such as described in hashicorp/terraform#5740:
```
resource "aws" "web" {
provider = "aws" {
region = "us-west-2"
}
}
```
We now return an error message - "hcl object keys must be a string" instead of crashing.
Fixes hashicorp/terraform#5740.

Return an error if object keys are not strings

---

hcl/fmtcmd/fmtcmd_test.go
hcl/printer/printer_test.go

The red CI build on Windows is making it harder to process actual bugs - neither printer or fmt are used in any HC projects currently so ignoring the tests on AppVeyor/Windows seems reasonable for now. At some point they need fixing to account for line endings.

Temporarily ignore printer and fmt tests on Windows

---

decoder_test.go
hcl/scanner/scanner.go
hcl/scanner/scanner_test.go
hcl/token/token.go
test-fixtures/multiline_indented.hcl
test-fixtures/multiline_no_hanging_indent.hcl

This PR adds support for the style of HEREDOC often used in Ruby which allows the terminating marker to be indented if the HEREDOC is started with the sequence "<<-" rather than the usual "<<". This allows users to express documents with more natural indentation:
```
resource "template_file" "test" {
template = <<-HEREDOC
First Line
Second Line
HEREDOC
}
```
Note that this does not attempt to add any semantics around removing hanging indent from the actual text of the document, so extra indentation would still be present. We could make use of the canonical style for HCL herre to remove the hanging indent in the style of Ruby which would probably be more predictable for users.
Fixes https://github.com/hashicorp/hcl/issues/9
cc @phinze, @mitchellh

Add support for indented HEREDOC terminators

---

hcl/printer/printer.go
hcl/printer/printer_test.go
hcl/printer/testdata/comment.golden
hcl/printer/testdata/comment_aligned.golden
hcl/printer/testdata/comment_standalone.golden
hcl/printer/testdata/complexhcl.golden
hcl/printer/testdata/empty_block.golden
hcl/printer/testdata/list.golden

Noticed that the `hclfmt` tool (which uses hcl/printer) was chomping
the trailing newline from config files.
Here we switch to the more conventional newline-at-EOF output.
In the process of changing this, I realized that:
* The printer_test.go build tag was wrong, so it wasn't running
* The format() test helper was not exercising Format
So both of those fixes are included here

printer: output EOF newline in formatted hcl

---

hcl/fmtcmd/fmtcmd.go
hcl/fmtcmd/fmtcmd_test.go

The fmtcmd tests weren't running before due to the same build tag
problem as #112, so didn't catch the fact that there was an extra
newline being added here, which is now doubled thanks to #112.
Fixing up the build tag reveals failing tests - removing the extra
newline fixes the tests.

fmtcmd: Remove extra newline

---

decoder_test.go
hcl/strconv/quote.go
hcl/strconv/quote_test.go
test-fixtures/escape.hcl

Fixes hashicorp/terraform#6359 and several
related issues by unescaping a double backslash within braces to a
single backslash.
This bumps into the bit of HIL that still hangs out in HCL - for values
that aren't interpolated, like Terraform's variable defaults - users
were unable to get a backslash to show up within `${}`.
That's because `${}` is handled specially to allow for, e.g., double
quotes inside of braces.
Here, we add `\\` as a special cased escape (along with `\"`) so users
can get backslashes in these scenarios by doubling them up.

strconv: Fix escaped backslashes \\ in braces ${}

---

decoder.go
decoder_test.go

Like encoding/json each exported struct field becomes a member of the object unless the field's tag is "-"

Ignore field when tag is "-" when decoding structs

---

hcl/fmtcmd/fmtcmd.go

This description was originally copied straight from gofmt[0]. But as noted
in hashicorp/terraform#6343, the "instead of rewriting" suggests that it
disables the `Write` option, whereas it is possible to enable both.
[0]: https://golang.org/src/cmd/gofmt/gofmt.go#L31

hcl/fmtcmd: Clarify docs for Options.Diff

---

hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

Fixes GH-127
As the title says.

hcl/scanner: handle \"\\0 input properly

---

decoder.go
decoder_test.go
test-fixtures/terraform_variable_invalid.json

Fixes https://github.com/hashicorp/terraform/issues/8295
When decoding an object into a struct where the object structure doesn't
match the Go struct structure, the case tested here would panic. This
introduces additional checks to guard against the edge case being hit to
avoid the panic.
The specific checks being added are: if an item being decoded into a
struct is a literal type, the item to be decoded must be non-nil in
order to use it. This isn't super clear and to be honest I also don't
fully understand it but this fixes the problem without introducing any
more test failures and without significant code complexity.

Fix panic when decoding invalid value structure into struct

---

hcl/ast/ast.go
hcl/parser/parser_test.go
hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

Fixes: https://github.com/hashicorp/terraform/issues/8477
The way the scanner works '/ foo' was actually valid comment syntax.
This obviously is not what we want. This modifies the scanner to verify
that '//' comments in fact have the second '/'.

hcl/scanner: single line '//' commments verify second '/'

---

decoder_test.go
json/parser/parser_test.go
json/parser/test-fixtures/bad_input_tf_8110.json
json/parser/test-fixtures/good_input_tf_8110.json
json/scanner/scanner.go
json/scanner/scanner_test.go
test-fixtures/interpolate.json

Related: https://github.com/hashicorp/terraform/issues/8110
At some point we ignored the " in interpolations. We do this for HCL and
it is correct but this is invalid JSON syntax and for JSON we've always
had the stance that we have to escape them.
This shows up in HCL as normal unescaped (because it only escapes it for the purpose of JSON), as the test shows in decode_test.go.

json: interpolations have to be escaped

---

hcl/ast/ast.go

While testing vault-secure-intro, the config file had an undesired `=` in the config, which was causing a panic.
Wrong input causing panic:
environment = "aws" {
}
Correct input:
environment "aws" {
}
This is where the investigation lead to.
All the tests pass.

Skip a nil item during filtering

---

README.md

It was unclear how nested object example in hcl would map to json. Readme now updated to include an example of the json equivalent to a hcl nested object

Added hcl to json example for nested objects

---

hcl/ast/ast.go

Reverts hashicorp/hcl#121
See discussion and test case on #121.

Revert "Skip a nil item during filtering"

---

.travis.yml
Makefile
appveyor.yml
decoder.go
decoder_test.go

A single JSON object with a single key and value of a another object fails to decode.

missing fields when decoding JSON

---

hcl/parser/parser_test.go
hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/comment_newline.golden
hcl/printer/testdata/comment_newline.input

This adds a special case to find comments that are first in a file to not prefix it with newlines and a test case for this. No other tests fail.

hcl/printer: file with only comments formats properly

---

json/parser/parser.go

Without this patch the `json/parser.Parser` did not fill the `hcl/ast.ObjectItem.Assign` property resulting in missing assignment operators, visible when printing it using the `hcl/printer` package. Please look at following example code demonstrating the issue:
```go
package main
import (
"os"
"github.com/hashicorp/hcl/json/parser"
"github.com/hashicorp/hcl/hcl/printer"
)
const input = `
{
"a": "b"
}
`
func main() {
ast, err := parser.Parse([]byte(input))
if err != nil {
panic(err)
}
err = printer.Fprint(os.Stdout, ast)
if err != nil {
panic(err)
}
}
```
When executed, this program printed `"a" "b"` to stdout which is missing the `=` character.
With the patch applied, the output is the correct version: `"a" = "b"`

json/parser: set Assign property when parsing object item

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/multiline_string.golden
hcl/printer/testdata/multiline_string.input

Fixes https://github.com/hashicorp/terraform/issues/9859
For strings that have more than one line, we should not indent the
follow-up lines.

hcl/printer: multiline strings don't indent lines 2+

---

decoder_test.go
hcl/scanner/scanner_test.go
hcl/strconv/quote.go
hcl/strconv/quote_test.go
hcl/token/token_test.go
test-fixtures/escape_backslash.hcl

🚧  **DO NOT MERGE YET**  🚧 
This changes the behavior of HCL to _completely ignore any escape sequences within `${}`_. This is likely to break some configurations that used this. However, it resulted in more broken behavior if used with HIL. 
The prior behavior caused problems because HCL would escape some things (escaped backslashes) and then HIL would do the same, or error for syntax/unescaped reasons. This double escape caused most practical configs to not work at all.
This change is slated for Terraform 0.8 when we can introduce BC-incompat.

[DO NOT MERGE YET] hcl: don't escape ANYTHING in ${}, let lower layer handle it

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/comment_multiline_indent.golden
hcl/printer/testdata/comment_multiline_indent.input

Fixes https://github.com/hashicorp/terraform/issues/6524
This makes it so that lines 2+ in a comment aren't indented when formatted. This fixes an issue where comments would just continue to indent infinitely.

hcl/printer: multiline comments shouldn't indent lines 2+

---

hcl/parser/parser_test.go

Tiny change! Two unit test cases were testing parsing of the same list of literals.

Remove duplicate unit test

---

hcl/parser/parser.go

We shouldn't output any text during parsing, that's just strange!
token.ILLEGAL happens when the scanner has an error. This error is
recorded in `scerr` during parsing which is eventually returned out.
Therefore, we handle the error properly. We can simply return a backup
error here in case we don't (scanner errors are checked first).

hcl/parser: don't print "illegal"

---

decoder.go
decoder_test.go

In my config file I have many time.Duration fields, which were decoded perfectly fine with JSON, but with HCL it panicked, so here is the fix that will allow to decode aliased int types, like time.Duration.

Try to use SetInt in case if possible

---

hcl/printer/nodes.go

The purpose of this change is so that the code is valid in Go < 1.7. I am using hcl/printer in spf13/viper#287. It requires tests in Go < 1.7, so this prevents that from passage. I did a work around using build constraints, but it is pretty ugly. It would be much better without that workaround being required and there will be no impact on hcl.

Modify new bytes.ContainsRune to backward compatible bytes.IndexRune

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/list.golden
hcl/printer/testdata/list.input

This is a weird formatting edge case that looks ugly but is the only syntax to make this work. See: https://github.com/hashicorp/terraform/issues/10947

hcl/printer: newline after heredoc items in lists

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/list.golden
hcl/printer/testdata/list.input
hcl/printer/testdata/object_with_heredoc.golden
hcl/printer/testdata/object_with_heredoc.input

https://github.com/hashicorp/terraform/issues/11208
This builds on #177 to support lists with a heredoc that is at the same line as the list bracket. See tests for example formatting.

hcl: print single heredoc elements properly

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/comment_object_multi.golden
hcl/printer/testdata/comment_object_multi.input

https://github.com/hashicorp/terraform/issues/11209
See the TF issue above for an example, and test cases for a fix. This
didn't affect any other formatting tests.

hcl/printer: format comments across multiple lines in an object

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/list_comment.golden
hcl/printer/testdata/list_comment.input

For lists that had an item on the same line as the opening bracket `[`, the trailing comment would be lost. This fixes that.
The formatting isn't perfect yet but I was focusing first on not losing the comment.

hcl/printer: preserve list comment on first line

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/empty_block.golden
hcl/printer/testdata/object_singleline.golden
hcl/printer/testdata/object_singleline.input

Fixes #161
See #161 and test cases for examples.

hcl/printer: format single line objects to not have newline between

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/comment_end_file.golden
hcl/printer/testdata/comment_end_file.input

https://github.com/hashicorp/terraform/issues/11585#issuecomment-276681290
This isn't perfect (leaves a dangling newline at the end of the file) but it looks a LOT better than previously. See the test cases for examples and the TF issue above, too.

hcl/printer: cleaner handling of standalone comments at end of file

---

hcl/printer/nodes.go
hcl/printer/testdata/object_singleline.golden
hcl/printer/testdata/object_singleline.input

Fixes https://github.com/hashicorp/terraform/issues/12017

hcl/printer: singleline objects followed by non-singleline need blank

---

json/parser/parser.go

Encountered while running `hcl.Decode()` on a JSON blob.

Return an error instead of printing stray `illegal\n` to stdout.

---

decoder.go

Using `*reflect.StructField` as map key results in a data race. I honestly
do not understand why yet and can only reproduce this in the consul
codebase with high concurrency but this patch fixes it.
The same problem also exists in mitchellh/mapstructure.
See https://github.com/mitchellh/mapstructure/pull/101

Fix data race in decodeStruct

---

hcl/ast/ast_test.go
hcl/fmtcmd/fmtcmd_test.go

It looks like Go 1.10 fails these. This makes the build green again.
/cc @mitchellh @jefferai

Fix broken formatting directives

---

hcl/printer/printer_test.go
hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

This changes fix two cases in which `printer.Format()` produced output that was not accepted by `parser.Parse()`:
1.  The input ends in `\x00`: the scanner accepted this, because nothing is following the null byte. The formatter, however, decides to add a newline at the end of the file, assuming that this would be a no-op. Upon re-parsing, the null byte is no longer the last character in the stream and produces an error.
1.  The input contains the U+E123 unicode codepoint: this codepoint is used internally by the formatter to do some postprocessing of the generated output. If the input contains that codepoint, the postprocessing removes semantically relevant information, for example the pound sign signifying the beginning of a comment. This leads to unparsable output.
I think that it's …

printer, scanner: Don't produce unparsable output.

---

hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

scanner: Update prevPos even when returning utf8.RuneError.

---

hcl/printer/printer_test.go
hcl/printer/testdata/object_with_heredoc.golden
hcl/printer/testdata/object_with_heredoc.input
hcl/scanner/scanner.go

This PR fixes two issues when parsing heredoc strings:
*   The regular expression was not anchored to the beginning of the line, allowing arbitrary garbage in front of the delimiter.
*   The regular expression did not accept an arbitrary number of cartridge returns. One optional cartridge return (`\r`) and one newline (`\n`) were considered a line break. If a line ends in multiple cartridge returns, e.g. `EOF\r\r\n`, it was not considered to end the heredoc string with delimiter `EOF`. However, the formatter removes one cartridge return, so that a repeated parsing *would* consider the same line to end the heredoc string, resulting in a different interpretation of the input.
In most cases parsing the output results in a syntax error, but it is fairly easy to create inputs that change …

scanner: Improve regular expression in "scanner".scanHeredoc().

---

hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

For example, the (Go quoted) input `\"\\00` creates the following stack trace:
```
panic: bytes.Buffer: UnreadRune: previous operation was not a successful ReadRune
goroutine 1 [running]:
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).unread(0xc420090270)
gopath/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:112 +0x245
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).scanDigits(0xc420090270, 0x0, 0x8, 0x3, 0x5c2005b740)
gopath/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:557 +0x1ba
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).scanEscape(0xc420090270, 0xc40000005c)
gopath/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:520 +0x181
github.com/hashicorp/hcl/hcl/scanner.(*Scanner).scanString(0xc420090270)
gopath/src/github.com/hashicorp/hcl/hcl/scanner/scanner.go:504 +0x2c3 …
```

scanner: Don't call unread() after reading EOF.

---

hcl/printer/printer_test.go
hcl/scanner/scanner.go
hcl/scanner/scanner_test.go

The existing check did not take into account that a leading `-` is not considered part of the anchor.

scanner: Fix detection of zero-length heredoc anchor.

---

hcl/parser/parser.go
hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/comment.golden
hcl/printer/testdata/comment.input
hcl/printer/testdata/comment_crlf.input

This fixes comment handling in situations such as:
```
everything = // comment
42
```
Previously the comment would "leak" to a later line, potentially disturbing heredoc markers (see the included test for a demonstration). 
Kudos to [dvyukov/go-fuzz](https://github.com/dvyukov/go-fuzz/) for finding this!

printer: Fix handling of line comments in multi-line statements.

---

hcl/printer/nodes.go
hcl/printer/printer_test.go
hcl/printer/testdata/list.golden
hcl/printer/testdata/list_comment.golden
hcl/printer/testdata/list_comment.input

This change splits out the formatting of simple single-line lists. A list is considered "simple" if all of its elements are on one line, all elements are literals (except heredoc) and there are no line comments. As an exception, a heredoc string is allowed when it is the only element in the list.
This fixes an issue with a single-line list with one element and a line comment. The formatter used to pull the closing bracket on the same line (after the comment), causing parse errors.

printer: Simplify the formatting of single-line lists.

---

decoder.go
decoder_test.go
test-fixtures/string.hcl

When we're decoding into a string value, convert the other literal types (FLOAT and BOOL) to strings as well. Previously, decoding would fail on an unexpected literal type.

Decode string booleans

---

README.md

Excited to see the `hcl2` stuff merged into this repository. :tada: 
This tiny PR updates the link references to the `spec.md` files which used to exist under the `hcl/` directory in the hcl2 repository.

Update specification file references in README.

---

appveyor.yml

In the long run we intend to transition to using CircleCI for all of the testing steps here, but we need to keep appveyor enabled here until we have both the HCL 1 and HCL 2 branches ready to use CircleCI, so this is just a minimal appveyor configuration for running our tests in a Windows environment in order to avoid errant test failures on PRs until we have completed the move fully to CircleCI.

build: A basic appveyor.yml

---

hclwrite/ast_body.go

Fixes #310
The type of `Body.items` is a `nodeSet` (That is, `map[*node]struct{}`),
so the order of the list returned by Body.Blocks () was unstable.

hclwrite: Fix unstable list returned by Body.Blocks()

---

hclwrite/generate.go
hclwrite/generate_test.go

- Updating `appendTokensForTraversalStep` to return an updated slice
- Adding a test to verify `Tokens`

fix for TokensForTraversal returning nil Tokens

---

hclwrite/ast_body.go
hclwrite/ast_body_test.go
hclwrite/ast_expression.go

We currently have functions for constructing new expressions from either constant values or from traversals, but some surgical updates require producing a more complex expression.
In the long run perhaps we'll have some mechanism for constructing valid expressions via a high-level AST-like API, similar to what we already have for structural constructs, but as a simpler first step here we add a mechanism to just write raw tokens directly into an expression, with the caller being responsible for making sure those tokens represent valid HCL expression syntax.
Since this new API treats the given tokens as unstructured, the resulting expression can't fully support the whole of the expression API, but it's good enough for writing in complex expressions without disturbing existing content …

hclwrite: Allow constructing expressions from raw tokens

---

go.mod
go.sum

This patch release includes a couple small bug fixes that don't affect HCL directly, and a slight improvement to error messages for failed conversions from boolean to string.
The primary goal of this upgrade is to ratchet dependents on HCL up to the newer version of cty in order to get those improved error messages, but during upgrading they may also benefit from the other bug fixes.

dependencies: go get github.com/zclconf/go-cty@v1.1.1

---

hclsyntax/expression.go
hclsyntax/parser.go
hclsyntax/parser_test.go
hclwrite/parser_test.go

Some `hclsyntax` callers make the (reasonable) assumption that the overall source range of an expression will be a superset of all of the ranges of its child expressions, for purposes such as extraction of source code snippets, parse tree annotation in hclwrite, text editor analysis functions like "go to reference", etc.
The `IndexExpr` type was not previously honoring that assumption, since its source range was placed around only the bracket portion. That is a good region to use when reporting errors relating to the index operation, but it is not a faithful representation of the full extent of the expression.
In order to meet both of these requirements at once, `IndexExpr` now has both `SrcRange` covering the entire expression and `BracketRange` covering the index part delimited by …

hclsyntax: Source range of IndexExpr, SplatExpr, and RelativeTraversalExpr must cover whole expression

---

hcldec/spec.go

The two cases where we decode attribute values should include the expression and `EvalContext` in any diagnostics they generate so that the calling application can give hints about the types and values of variables that are used within the expression.
This also includes some adjustments to the returned source ranges so that both cases are consistent with one another and so that both indicate the entire expression as the `Subject` and include the attribute name in the `Context`. Including the whole expression in the range ensures that when there's a problem inside a tuple or object constructor, for example, we'll show the line containing the problem and not just the opening `[` or `{` symbol.
---
We don't have any specific tests in HCL for the metadata on diagnostics so in order to test …

hcldec: Improved context for expression diagnostics

---

ext/customdecode/README.md
ext/customdecode/customdecode.go
ext/customdecode/expression_type.go
ext/tryfunc/README.md
ext/tryfunc/tryfunc.go
ext/tryfunc/tryfunc_test.go
ext/typeexpr/README.md
ext/typeexpr/type_type.go
ext/typeexpr/type_type_test.go
go.mod
go.sum
hcldec/spec.go
hclsyntax/expression.go
integrationtest/convertfunc_test.go
integrationtest/hcldec_into_expr_test.go

These changes include some new capabilities for those building languages on top of HCL, but I'm going to start by talking about the main motivating use-cases that led me here, which all HCL functions that require some special handling for one or more of their arguments:
* `convert(value, type)` for generalized type conversion using a type expression instead of a value expression in the second argument, like `convert([], set(string))`. This can be useful when a value is being used as part of defining an API, like in [Terraform Output Values](https://www.terraform.io/docs/configuration/outputs.html), where we can be explicit about what result type we're intending and see an error if the value is not sufficiently close to that type to be converted successfully. (Terraform does already have …

Custom expression decoding in function calls and hcldec specs

---

gohcl/doc.go

This documents the "optional" attribute, which allows you to specify an
attribute that is optional when parsing.

gohcl: document optional attribute

---

go.mod
go.sum
hclsyntax/parser.go
hclsyntax/parser_template.go
hclsyntax/token.go
hclwrite/tokens.go
json/scanner.go
pos_scanner.go

HCL uses grapheme cluster segmentation to produce accurate "column" indications in diagnostic messages and other human-oriented source location information. Each new major version of Unicode introduces new codepoints, some of which are defined to combine with other codepoints to produce a single visible character ([grapheme cluster](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries)).
We were previously using the rules from Unicode 9.0.0. This change switches to using the segmentation rules from Unicode 12.0.0, which is the latest version at the time of this commit and is also the version of Unicode used for other purposes by the Go 1.14 runtime.
HCL does not use text segmentation results for any purpose that would affect the meaning of decoded data extracted from HCL files, …

Use Unicode 12.0.0 grapheme cluster segmentation rules

---

json/public_test.go
json/scanner.go
json/scanner_test.go

When scanning JSON, upon encountering an invalid token, we immediately return. Previously this return happened without inserting an EOF token. Since other functions assume that a token sequence always ends in EOF, this could cause a panic.
This commit adds a synthetic EOF token after the invalid token before returning. While this does not match the real end-of-file of the source JSON, it is marking the end of the scanned bytes, so it seems reasonable.
Fixes #339

json: Fix panic when parsing malformed JSON

---

hclwrite/examples_test.go
hclwrite/generate.go
hclwrite/generate_test.go

The previous syntax for object and map values was a single line of key-value pairs. For example:
```hcl
object = { bar = 5, baz = true, foo = "foo" }
```
This is very compact, but in practice for many HCL values, less readable and less common than a multi-line object format. This commit changes the generated output from hclwrite to one line per attribute.
Examples of the new format:
```hcl
// Empty object/map is a single line
a = {}
// Single-value object/map has the attribute on a separate line
b = {
bar = 5
}
// Multi-value object/map has one line per attribute
c = {
bar = 5
baz = true
}
```

hclwrite: Generate multi-line objects and maps

---

hclwrite/parser.go
hclwrite/parser_test.go

This PR allows `hclwriter` to handle dot syntax for index accesses, e.g.:
```hcl
module "test" {
test = kubernetes_config_map.test.metadata.0.name
}
```
Previously, attempting to partition on an open bracket caused a panic:
https://github.com/hashicorp/hcl/blob/hcl2/hclwrite/parser.go#L408
This PR adds a `PartitionTypeOk` that is a copy of `PartitionType`. It returns the same values, plus an `ok` bool  signifying that the token type was found. Otherwise, it returns zero-value `inputTokens` objects and a `false` boolean indicating that a partition token could not be found.
The approach to detecting that a traversal is `.#` style is admittedly fairly naive. However, adding a passing test on `a = foo[bar.baz]` makes me feel a bit more confident. 
Related bug reports: …

hclwrite: handle legacy dot access of numeric indexes

---

hclsyntax/parser.go
hclwrite/parser_test.go

The following expression caused a panic in hclwrite:
```hcl
a = foo.*
```
This was due to the unusual dotted form of a full splat (where the splat operator is at the end of the expression) being generated with an invalid source range. In the full splat case, the end of the range was uninitialized, which caused the token slice to be empty, and thus the panic.
This commit fixes the bug, adds test coverage, and includes some bonus tests for other splat expression cases.
Bug reported in apparentlymart/terraform-clean-syntax#7

hclwrite: Fix panic for dotted full splat (foo.*)

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Update: I ended up tackling two adjacent bugs at once. 
-----
Previously functions such as `concat()` would result in a panic if there
was a null element and a sequence, as in the included test. This PR adds
a check if the error index is outside of the range of arguments and
crafts an error that references the entire function instead of the null
argument.
Tested locally to confirm that this fixes a reported terraform panic:

hclsyntax: address multiple issues with sequences (...)

---

hcldec/spec.go
hcldec/spec_test.go

This adds ValidateFuncSpec, a new decoder Spec that allows one to add
custom validations to work with values at decode-time.
The validation is run on the value after the wrapped spec is applied to
the expression in question. Diagnostics are expected to be returned,
with the author having flexibility over whether or not they want to
specify a range; if one is not supplied, the range of the wrapped
expression is used.

hcldec: add ValidateSpec

---

hclsyntax/token.go

Fixes #376
before
```
$ echo 'foo = a | b' | go run ./cmd/hclfmt/main.go -check
Error: Unsupported operator
on <stdin> line 1:
1: foo = a | b
Bitwise operators are not supported. Did you mean boolean OR ("&&")?
Error: Missing newline after argument
on <stdin> line 1:
1: foo = a | b
An argument definition must end with a newline.
one or more files contained errors
exit status 1
```
after
```
$ echo 'foo = a | b' | go run ./cmd/hclfmt/main.go -check
Error: Unsupported operator
on <stdin> line 1:
1: foo = a | b
Bitwise operators are not supported. Did you mean boolean OR ("||")?
Error: Missing newline after argument
on <stdin> line 1:
1: foo = a | b
An argument definition must end with a newline.
one or more files contained errors
exit status 1
```

Fix a wrong error message for bitwise OR

---

json/parser.go
json/parser_test.go
json/public.go
json/public_test.go

Similar to `hclsyntax.ParseConfig`, this PR changes the start position to be passed to the `json.Parse` function.
This feature is necessary to transfer `hcl.Block` via RPC. We need to be able to specify the start position when we take a partial JSON and parse it on the other side. See also #332 #381 
However, I understand that this change breaks backward compatibility. I propose this change for interface consistency, but if you care about compatibility, I could add a parsing function that accepts positions (e.g. `json.ParseWithPos`). Please tell me your opinion.

json: Add json.ParseWithStartPos function

---

hclsyntax/token.go
hclsyntax/token_test.go

It seems to be somewhat common for someone to share HCL code via a forum or a document and have the well-meaning word processor or CMS replace the straight quotes with curly quotes, which then lead to confusing errors when someone copies the result and tries to use it as valid HCL configuration.
Here we add a special hint for that, giving a tailored error message instead of the generic "This character is not used within the language" error message.
HCL has always had some of these special hints implemented here, and they were originally implemented with special token types to allow the parser to handle them more easily inline. However, we later refactored to do the check all at once inside the `Lex*` family of functions, prior to parsing, so it's now relatively straightforward to handle …

hclsyntax: Tailored error for "curly quotes"

---

json/parser.go
json/public.go
json/public_test.go

Fixes #332 
Similar to `hclsyntax.ParseExpression`, This PR adds a function that parses a part of the JSON source.
Initially, I was looking for a way to transfer `json.expression` with RPC, but following the suggestion of @apparentlymart, I'm now thinking of sending text and parsing the text passed in each as an expression. This is a missing piece to achieve that.

json: Add ParseExpression function

---

hclsyntax/expression_template.go
hclsyntax/expression_template_test.go

If a template expression interpolates values which have marks, we should apply all of those marks to the output value. This allows template expressions to function like native cty functions with respect to marks.

hclsyntax: Pass marks through template expressions

---

hclsyntax/expression_template_test.go
ops.go
ops_test.go

If a `cty.Map` was marked, traversing it by path would previously panic. From the existing code, this may have been by design, but it does make it particularly difficult to use marks with Terraform values. This commit fixes the panic by explicitly dropping marks when checking if a map has a given attribute.
PR includes a new test of traversing a marked map to demonstrate the use case for this.
@apparentlymart, I'm concerned that this may be against the goals of how marks are supposed to be used, but I can't see any reasonable alternative here. What do you think?

Fix panic traversing marked map

---

hclsyntax/expression.go
hclsyntax/expression_test.go

A for expression over a marked collection should result in a new collection with the same marks. Previously this would fail with a type error.

hclsyntax: Fix for expressions over marked values

---

hcl/ast/ast.go

When decoding a value which contains an object (with braces) but no content, there is no first Item to use for the position in errors.  Instead return an undefined tokenPos.

Return an undefined Pos for an empty ObjectList

---

gohcl/decode.go
gohcl/decode_test.go
gohcl/doc.go
gohcl/schema.go

Structs can specify the "body" struct tag to capture the entire block
body. This does NOT act as "remain" where leftover fields are
non-erroneous. If you want leftover fields to be allowed, a "remain"
field must ALSO be present.
This is used to capture the full block body that was decoded for the
block. This is useful if you want to ever redecode something differently
(maybe with a different EvalContext) or partially decode something but
redecode the entire value.

"body" struct tag to capture entire body for a block decode

---

hclwrite/ast_block.go
hclwrite/ast_block_test.go

The `hclsyntax` package permits block labels to be blank quoted strings, and defers to the application to determine if this is valid or not. This commit updates `hclwrite` to allow the same behaviour.
This is in response to [an upstream bug report on Terraform](https://github.com/hashicorp/terraform/issues/26960), which uses `hclwrite` to implement its `fmt` subcommand. Given a block with a blank quoted string label, it currently deletes the label when formatting. This is inconsistent with Terraform's behaviour when parsing HCL, which treats empty labels differently from missing labels:
```hcl
provider "" {}
provider {}
```
```shellsession
$ terraform init
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so …
```

hclwrite: Allow blank quoted string block labels

---

hclsyntax/expression.go
hclsyntax/expression_test.go

According to https://discuss.hashicorp.com/t/pattern-to-handle-optional-dynamic-blocks/2384/2
`null[*]` is defined and should return an empty tuple. The logic in
SplatExpr.Value() is slightly wrong thought as it returns early with a
dynamic value even when the value is actually known to be null.
The fix is easy, just check for null sources first, then for dynamic
values. I added a test for this in TestExpressionParseAndValue().

Fix the logic for `null[*]`

---

gohcl/decode.go
gohcl/decode_test.go

Currently, if user tries to decode such scenario, it results in
"slice index out of range".
Fixes regression introduced in 42351b1d15716a53accce7144d13df5606d56b19.
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

gohcl/decode.go: fix decoding value slices

---

ops.go
ops_test.go

We need to unmark the result of `HasIndex` in order to compare it with true or false without a panic.
Basically the same fix as #406. Downstream bug in Terraform `sensitive` values: https://github.com/hashicorp/terraform/issues/27041

Fix panic traversing marked list

---

hclsyntax/expression.go
hclsyntax/parser.go
hclsyntax/structure_at_pos_test.go
hclsyntax/walk_test.go
hclwrite/parser_test.go

So far the expression parentheses syntax has been handled entirely in the parser and has been totally invisible in the AST. That's fine for typical expression evaluation, but over the years it's led to a few quirky behaviors in less common situations where we've assumed that all expressions are covered by the AST itself or by the source ranges that the AST captures.
In particular, `hclwrite` assumes that all expressions will have source ranges that cover their tokens, and it generates an incorrect physical syntax tree when the AST doesn't uphold that.
After resisting through a few other similar bugs, this commit finally introduces an explicit AST node for parentheses, which makes the parentheses explicit in the AST and captures the larger source range that includes the `TokenOParen` and …

hclsyntax: Explicit AST node for parentheses

---

hclwrite/format.go
hclwrite/format_test.go

A space should not be added after a bang (`!`) - which is used for negation.
See: https://www.terraform.io/docs/configuration/expressions.html#logical-operators

hclwrite: do not add space after a bang

---

hclsyntax/expression.go
hclsyntax/expression_test.go

In conditional expressions that involve a marked value, unmark the value before inspecting its truthiness. This avoids a mark panic in cty when checking the value. Related to https://github.com/hashicorp/terraform/issues/27107

Unmark conditional values before checking their truthiness

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Functions which accept multiple parameters can be called with the expansion operator, `...`. When doing so, we must unmark the expanded argument value before transforming it into a collection of function arguments. To ensure that any marks applied to the collection are preserved, we transfer the collection marks to the individual elements as we build the argument list.
Downstream issue: [#27220](https://github.com/hashicorp/terraform/issues/27220)

hclsyntax: Fix panic when expanding marked funargs

---

hclsyntax/expression.go
hclsyntax/expression_test.go

When evaluating an HCL expression attempting to use a marked value as an object key, return an error rather than falling through to the cty panic.
The error text mimics similar errors in the area, but could be more similar to #433 (or changed in either location) if preferred.

Error if attempting to use marked value as key

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Rather than allowing a panic to occur, return an error for "Invalid object key" if a user attempts to write a for expression that would convert the marked value to an unmarked string (by using it as the object key).
Prior to this change, the following code would panic:
```
> local.baz
{
"a" = (sensitive)
"b" = "dog"
}
> {for  v in local.baz: v => 1 }
```
After:
```
> {for  v in local.baz: v => 1 }
>  
Error: Invalid object key
on <console-input> line 1:
(source code not available) # Terraform console usage
Marked values cannot be used as object keys.
```

Return an error for invalid for expressions with marks

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Fixes [this downstream Terraform bug](https://github.com/hashicorp/terraform/issues/27329). I couldn't find any other instances of calling `LengthInt` on a possibly-marked collection.

hclsyntax: Fix panic for marked collection splat

---

hclsyntax/expression_template.go
hclsyntax/expression_template_test.go

Fixes [this downstream Terraform bug](https://github.com/hashicorp/terraform/issues/27336). I couldn't find any other instances of calling `ElementIterator` on a possibly-marked collection (except in splat expressions, which is fixed by #436).

hclsyntax: Fix panic for marked template loops

---

hclsyntax/expression.go
hclsyntax/expression_test.go

These test cases both panic without the associated changes, because `.False()` on a marked value is invalid.
If the conditional expression in a for expression evaluates to a marked value, we need to ignore the marks before testing it. Since this result will not interpolate into the result, dropping the mark here seems reasonable for now.

hclsyntax: Fix for expression marked conditional

---

hclsyntax/expression.go
hclsyntax/expression_test.go

This adjusts prior behavior that would error to now allow keys that are marked; those marks are removed in evaluation in order to give a valid string for the map key, but the resulting object or tuple is marked as a whole with whatever mark the key contained, ensuring marks are maintained.
Follow-on work to #434

Mark objects with keys that are sensitive

---

hcltest/mock.go
hcltest/mock_test.go

Add an ExprMethod so that the mock expressions can be handled by the
hcl.ExprMap function.
Added basic tests for both ExprList and ExprMap

add an ExprMap method to the mock expression

---

ops.go
ops_test.go

Index keys must be unmarked to convert them to a primitive type.
Add tests for overall `Index` test coverage.

avoid panics with marked Index key values

---

ext/dynblock/expand_body_test.go
ext/dynblock/unknown_body.go
hcldec/spec.go

The dynblock extension paired with `hcldec` previously used a single object with unknown attributes as a sentinel to indicate that a decoded `dynamic` block was unknown. This however poses multiple problems with consumers of the data which are not aware of the dynamic construct, since they may misinterpret the number of values, and can be confused when known values are mixed with the sentinel value. 
Rather than using a sentinel value within the container, here we propose to ensure a decoded block container which contains any `dynamic` block with an unknown `for_each` argument will result in an entirely unknown value. This better serves the purpose of the original sentinel value, as there is no other way to _assign_ an unknown value to a block container, and allows consumers to understand …

dynblock,hcldec: Decode unknown dynamic block bodies as entirely unknown values

---

hclsyntax/parser_template.go

It's a common error to accidentally include a `${` intended to be processed as part of another language after HCL processing, such as a shell script or an AWS IAM policy document.
Exactly what sort of error will appear in that case unfortunately depends on the syntax for that other language, but a lot of them happen to end up in the codepath where we report the "Extra characters after interpolation expression" diagnostic message. For that reason, this extends that error message with an additional hint about escaping.
I've also included a special case for colons because they happen to arise in both Bash and AWS IAM interpolation syntax, albeit with different meanings. The specialized error message doesn't really say anything the generic one doesn't, but it does explicitly identify the …

hclsyntax: Hint about possible unescaped ${ for other languages

---

hclsyntax/parser.go
hclsyntax/parser_test.go

If a block label had an invalid quoted string literal, the parser would previously create label ranges with uninitialized `End` values. For Terraform, this would eventually percolate into invalid diagnostic output due to the assumption that the end of a range is always greater than or equal to the start: see https://github.com/hashicorp/terraform/issues/28587 and https://github.com/hashicorp/terraform/pull/28598
This commit addresses this by using the terminating token's position as the end of the range, even if it's not a closing quote.

Fix parseQuotedStringLiteral zero end range

---

ext/tryfunc/tryfunc_test.go

This PR adds some test coverage to illustrate handling marked inputs in `TryFunc`.  `TryFunc` preserve marks on return values, including preserving marks on collections if the result is an element of said collection.

ext: TryFunc tests to document handling of marked values

---

hclsyntax/expression.go
hclsyntax/expression_test.go

When a function returns a `functions.ArgError` it's supposed to set the argument index to a valid index within the range of the given argument slice.
However, we typically try to be robust in the face of incorrectly-implemented functions, so rather than panicking in that case
as we would've before we'll now return a slightly-less-precise error message.
The `if i > len(e.Args)-1` case in the previous code here was actually trying to handle this situation before, but it didn't quite manage to do it because it was incorrectly referring to `e.Args` rather than `args` (so it couldn't take into account expanded arguments) and because it incorrectly assumed that there would always be more declared parameters than arguments (which is only true when there's a variadic parameter that has no …

hclsyntax: Don't panic when function returns invalid ArgError

---

hclsyntax/spec.md

In the text talking about how to resolve the ambiguity between `for` expressions and values/keys called `for` there was previously an incorrect statement about the behavior of `(for)` as an object key.
That situation causes HCL to take the value of a variable named `for`. To get the literal string `"for"` we must instead write the name in quotes, similarly to how we'd represent a key string that includes characters which HCL doesn't admit into an identifier.
[Rendered version of the relevant section](https://github.com/hashicorp/hcl/blob/b-hclsyntax-spec-for-key/hclsyntax/spec.md#collection-values)

hclsyntax: Fix incorrect examples of object expressions in the spec

---

ops.go
ops_test.go

When we first implemented these helpers we tried to anticipate a few situations that seemed likely to come up and implement specialized error messages for them, but in the intervening years we've seen a number of other situations crop up with some regularity.
Given that, I've added a few more specialized error message cases to both of these functions, so we'll return the most generic error messages in fewer situations.
Because `hcl.Index` and `hcl.GetAttr` are quite general functions used for lots of different application-specific purposes alongside their part in the implementation of the index and attribute access operators, I've intentionally kept these messages quite vague in the suggestions they make, which does mean that unfortunately users will probably need to do some further …

hcl: More helpful error messages in Index and GetAttr

---

hclsyntax/expression_template.go
hclsyntax/expression_template_test.go

Do not discard marks from unknown values when processing string
templates.
Part of the fix for https://github.com/hashicorp/terraform/issues/29173

hclsyntax: maintain marks from unknown values

---

ext/dynblock/expand_body.go
ext/dynblock/expand_body_test.go
hcldec/spec.go

Always attempt to decode dynamic blocks to provide validation. If the
iterator is unknown the value will be discarded, but the diagnostics are
still useful to unsure the structure is correct.

decode unknown dynamic blocks to ensure they are valid

---

guide/go_patterns.rst

The example below taken from the guide
> ```hcl
> variable "network_numbers" {
>   type = list(number)
> }
> ```
>
> In this example, the variable "network_numbers" block makes `var.base_network_addr` available to expressions,
should instead read:
```diff
In this example, the `variable "network_numbers"` block makes
- `var.base_network_addr`
+ `var.network_numbers`
available to expressions,
```

Fix wrong var name in HCL guide

---

hclsyntax/structure.go

As discussed via Slack this field is no longer (and probably never was) used for reporting missing items.
Instead `Body` has a dedicated method for this:
https://github.com/hashicorp/hcl/blob/2ebbb5d2dcc67881774d2b81d1497a55452e890f/hclsyntax/structure.go#L281-L287

hclsyntax: Clarify Body.EndRange comment

---

hclsyntax/navigation_test.go
hclsyntax/structure.go

This patch fixes a minor discrepancy between `hclsyntax` and `hcl` in how DefRange is computed for a block.
DefRange of the "higher-level" `hcl.Block` (typically used by most applications) ends with the last label.
DefRange of the "lower-level" `hclsyntax.Block` ended with the opening brace `{` (i.e. at least 2 characters further).
Here we align the low-level API with the high-level one, meaning that most consumers should not be affected by this change, partly because they use `hcl.Block` (which isn't changing) or because they use DefRange to inform some non-critical decisions such as enriching diagnostics.
--- 
I ran into this discrepancy when working on adding support to JSON syntax to the language server in https://github.com/hashicorp/hcl-lang/pull/88

Align `hcl.Block` & `hclsyntax.Block` `DefRange`

---

hclsyntax/parser.go
hclsyntax/parser_template.go
hclsyntax/parser_test.go
specsuite/tests/structure/blocks/single_unclosed.t

For parts of the input that are delimited by start and end tokens, our typical pattern is to keep scanning for items until we reach the end token, or to generate an error if we encounter a token that isn't valid.
In some common examples of that we'll now treat `TokenEOF` as special and report a different message about the element being unclosed, because it seems common in practice for folks to leave off closing delimiters and then be confused about HCL reporting a parse error at the end of the file. Instead, we'll now report the error from the perspective of the opening token(s) and describe that construct as "unclosed", because the EOF range is generally less useful than any range that actually contains some relevant characters.
This is not totally comprehensive for all cases, but covers …

hclsyntax: Special error messages for EOF in certain contexts

---

hclsyntax/expression.go
hclsyntax/expression_test.go

When a splat expression is used to upgrade an unknown value to a list with a single value, the result must be entirely unknown. 
Using a splat expression to expand a single non-list value will result in a list with a single value, unless that value is null, in which case it will result in an empty list. This means that if `ukstr` is an unknown string value, then `unkstr[*]` could either result in a list of 1 string value, or an empty list, hence the result of `unkstr[*]` must be entirely unknown.

splat expression upgrading an unknown value should be unknown

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Follow up for #493, which ensured the value of an upgraded splat expression on an unknown value is unknown, but could result in the wrong type. When the previous PR was updated to allow specific types for expressions with attribute selectors after the splat, the resulting types were still unknown tuples even though the number of elements could not be determined. 
When upgrading an unknown splat value, the resulting collection may have 0 elements if the value ends up being `null`. Since the final result may be a tuple type with 0 or 1 elements, the unknown value must also be dynamic.

unknown upgraded splat values may have no elements

---

hclwrite/generate.go
hclwrite/generate_test.go
hclwrite/tokens.go

Add several function for `SetAttributeRaw()` enhancement, which include ways transfer `Traverse` to `Tokens`
`TokensForListTraversal` support for list `traversal`, mentioned in #347 
struct like this
```golang
// block for
func main() {
file := NewEmptyFile()
body := file.Body()
block := body.AppendNewBlock("resource", []string{"foo"})
tokens := TokensForListTraversal([]hcl.Traversal{
{
hcl.TraverseRoot{Name: "root"},
hcl.TraverseAttr{Name: "attr"},
},
{
hcl.TraverseRoot{Name: "second"},
hcl.TraverseAttr{Name: "attr"},
},
})
block.Body().SetAttributeRaw("bar", tokens)
fmt.Printf("%s", file.Bytes())
}
```
and got
```
resource "foo" {
bar = [root.attr,second.attr]
}
```
`TokensForListTokens` for mixed `traversal` value and cty value,  trans all traversal and cty value into `Tokens` , then …

hclwrite: add support for tuple,nested object and function call

---

hclsyntax/public_test.go
hclsyntax/token.go

Hello, team. First of all, thank you for sharing this library.
While working on an internal project that makes use of this library to parse `.hcl` files to retrieve a list of used modules, I added some benchmarks and found that one of the bottlenecks that I had was in the `hclsyntax.LexConfig`. Further inspection highlighted `checkInvalidTokens` as one of the culprits (the other being `emitToken` which is in a generated file and thus I didn't want to mess much with).
I took the liberty to add a benchmark for `LexConfig` with a rather small HCL file, but that serves the purposes of finding if I was able to improve the results. Then I proceeded to run the benchmarks in the original code and found this results (only showing one line for brevity):
```
$ go test -benchmem -bench=. …
```

Increase performance and reduce allocations in `hclsyntax.LexConfig`

---

hclsyntax/scan_tokens_test.go

This PR adds two unit tests demonstrating invalid heredoc syntax, intended as a discussion point.
The following Terraform variable definition yields an error (https://github.com/hashicorp/terraform/issues/25410):
```hcl
policy = <<EOF 
{
"hello": "hi"
}
EOF
```
Note the single whitespace character following "<<EOF" on the first line. Adding a matching whitespace character after the final "EOF" does not make it valid.
This is correct behaviour according to the HCL [spec](https://github.com/hashicorp/hcl/commit/2ebbb5d2dcc67881774d2b81d1497a55452e890f):
```ebnf
TemplateExpr = quotedTemplate | heredocTemplate;
quotedTemplate = (as defined in prose above);
heredocTemplate = (
("<<" | "<<-") Identifier Newline
(content as defined in prose above)
Identifier Newline
);
```
Since `Identifier` …

hclsyntax: test for invalid whitespace heredoc

---

gohcl/decode.go
gohcl/doc.go

This commit fixes a clause in the `gohcl` package documentation which incorrectly states that HCL blocks could be decoded into `hcl.Body` and `hcl.Block` types.
It also removes some code paths in `decodeBlockToValue()` that _appeared_ to handled these cases. In practice, these paths were unreachable anyway due to various reflection-based type checks made before `decodeBlockToValue()` is
called.
/cc @apparentlymart 
Fixes #505

gohcl: Fix docs about supported types for blocks.

---

json/is.go

Create exported methods so that we can determine if the underlying type of an `hcl.Expression` originated from a JSON document.

json: Functions for determining if an expression or body is a JSON one

---

hclsyntax/expression.go
hclsyntax/expression_test.go
hclsyntax/expression_vars_gen.go

For a long time now we've had a very simplistic error message for the case of conditional expression result arms not having the same type, which only works for situations where the two types have differing "friendly names" down in the cty layer.
Unfortunately due to the typical complexity of the structural type kinds (object and tuple types) their friendly names are just "object" and "tuple", which tends to lead us to seemingly-incorrect error messages like:
The true and false result expressions must have consistent types.
The given expressions are object and object, respectively.
This changeset then is an attempt to use some more specialized messaging in some of the situations that led to that sort of weird message before. In particular, this handles:
- both types are object types but …

hclsyntax: Improve conditional type mismatch errors (somewhat)

---

hclwrite/format.go

`nilToken` should never be modified.
Replaced to `continue` to avoid race conditions. 
More details in #533 .

format.go nilToken not 'thread' safe

---

go.mod
go.sum

The main motivation here is that we were apparently using bit shifting with signed shift amounts even though modern Go toolchains seem to raise that as an error (when using analysis tools like `gopls`, at least) if the `go.mod` file selects a language version less than Go 1.13.
Go 1.17 is therefore newer than we strictly need to solve that particular problem, but gets us caught up with a relatively recent release of the language. This alone doesn't break compatibility for anyone using older versions of Go with HCL, since the Go toolchain will still attempt to compile modules targeting later versions and will only mention the newer language version if compilation would already have failed for some other reason.

go.mod: Specify that we use the Go 1.17 language in this module

---

ext/typeexpr/defaults.go
ext/typeexpr/defaults_test.go
ext/typeexpr/get_type.go
ext/typeexpr/get_type_test.go
ext/typeexpr/public.go

This commit extends the type expression package to add two new features:
- In constraint mode, the `optional(...)` modifier can be used on object attributes to allow them to be omitted from input values to a type conversion process. Any such missing attributes will be replaced with a `null` value of the appropriate type upon conversion.
- In the new defaults mode, the `optional(...)` modifier takes a second argument, which accepts a default value of an appropriate type. These defaults are returned alongside the type constraint, and may be applied prior to type conversion through the new `Defaults.Apply()` method.
This change is upstreamed from Terraform, where optional object attributes have been available for some time. [The defaults functionality is …

typeexpr: Optional object attributes with defaults

---

ext/typeexpr/get_type.go
ext/typeexpr/get_type_test.go

When parsing optional object attribute defaults, we previously verified that the default value was convertible to the attribute type. However, we did not keep this converted value.
This commit uses the converted default value, rather than delaying conversion until later. In turn this prevents crashes when transforming collections which contain objects with optional attributes, caused by incompatible object types at the time of defaults application.
Fixes downstream issue hashicorp/terraform#31844

ext/typeexpr: Convert defaults for optional attrs

---

hclsyntax/spec.md

"within within" should be "within"

Fix documentation typo

---

ext/typeexpr/get_type_test.go
go.mod
go.sum

Previously, in the example test cases the empty default collection would be returned with the optional metadata embedded even though the default value should be a concrete value. This was fixed in the latest release of go-cty, and so was fixed here by pulling the latest go-cty.
* ext/typeexpr: Ensure default values do not have optional metadata attached. This prevents crashes when default values are inserted into concrete go-cty values that have also been stripped of their optional metadata.

Strip optional metadata from empty default collections

---

ext/typeexpr/defaults.go
ext/typeexpr/defaults_test.go

Instead of relying on the go-cty built in traversal functions we can iterate through the values when applying defaults ourselves.
This gives an advantage as we can choose when or when not to unify types. This PR introduces a small behaviour change that demonstrates the advantage. Previously, any objects or maps that had any defaults inserted would always be returned as objects to ensure there were no collisions in collections due to type differences. Now we automatically attempt to unify collection typesusing the go-cty convert package. If conversion is not possible we default to returning safe types (eg. tuples and objects) but if conversion is possible we can return the originally requested type.

Apply defaults using custom traversal of types

---

.github/workflows/push.yml

The intention here is to reduce the security risk posed by the supply chain - i.e. externally maintained GitHub Actions.
--- 
Note that I also bumped the major versions of both Actions, which _should_ not make a visible difference. I believe the main reason for the major bump was NodeJS version, where the old version either already is or soon will be EOL anyway, so this is somewhat necessary and optimistic step.

github: Pin external GitHub Actions to hashes

---

.github/workflows/push.yml
hclwrite/format.go
hclwrite/round_trip_test.go

This fixes a data race in `formatSpaces()` by inlining shared state into the caller.
Before
```go test ./hclwrite/... -race
==================
WARNING: DATA RACE
Write at 0x0000017bf900 by goroutine 14:
github.com/hashicorp/hcl/v2/hclwrite.formatSpaces()
/Users/ryan/code/hashi/hcl/hclwrite/format.go:127 +0x29d
github.com/hashicorp/hcl/v2/hclwrite.format()
/Users/ryan/code/hashi/hcl/hclwrite/format.go:36 +0x6c
github.com/hashicorp/hcl/v2/hclwrite.TokensForValue()
/Users/ryan/code/hashi/hcl/hclwrite/generate.go:25 +0x8a
github.com/hashicorp/hcl/v2/hclwrite.NewExpressionLiteral()
/Users/ryan/code/hashi/hcl/hclwrite/ast_expression.go:61 +0x97
github.com/hashicorp/hcl/v2/hclwrite.(*Body).SetAttributeValue()
/Users/ryan/code/hashi/hcl/hclwrite/ast_body.go:167 +0xd4 …
```

hclwrite: fix data race in formatSpaces()

---

hclsyntax/spec.md

The current spec appears to suggest that the bang is a binary operator, which would enable
expressions such as `foo ! bar`.
https://github.com/hashicorp/hcl/blob/main/hclsyntax/parser.go#L1070 seems to suggest this is only
a unary operator.

Update spec.md to avoid suggesting ! is a binary operator

---

hclsyntax/spec.md

Hi!
According to
https://developer.hashicorp.com/terraform/language/expressions/types#maps-objects
"Key/value pairs can be separated by either a comma or a line break."
But, the documentation here indicates that they may only be separated by a comma.
This is a little change to the docs to include the possibility of separating object elements by a line break.
thanks
Brian

Object elements can be separated by comma or newline

---

cmd/hclfmt/main.go

this is faster for large trees and also helps to make tools like            
[treefmt](https://github.com/numtide/treefmt) to work, since it does not    
update the mtime of the file.

hclfmt: avoid rewrites when there are no changes in a file

---

hclsyntax/expression_template_test.go
hclsyntax/parser_template.go
hclsyntax/parser_test.go

When processing a template string, the lexer can emit multiple string literal tokens for what ought to be a single string literal. This occurs when the string contains escape sequences, or consecutive characters which are indistinguishable from escape sequences at tokenization time.
This leads to a confusing AST and causes heuristics about template expressions to fail. Specifically, when parsing a traversal with an index, a key value containing an escape symbol will cause the parser to generate an index expression instead of a traversal.
This commit adds a post-processing step to the template parser to meld any sequences of string literals into a single string literal. Existing tests covered the previous misbehaviour (several of which had comments apologizing for it), and have been …

Meld consecutive template string literals

---

hclsyntax/expression_test.go
hclsyntax/parser.go
hclsyntax/parser_test.go

Closes https://github.com/hashicorp/hcl/issues/582
Passing tests suggest this isn't breaking anything else, but I'm open to suggestions for any more (careful) changes to avoid any unforeseen consequences.

hclsyntax: Report correct Range.End for FunctionCall w/ incomplete arg

---

traversal_for_expr.go

Remove consecutive occurrences of 'the'
`s/the the /the /g`

Typo fix: Consecutive occurrences of 'the'

---

ext/typeexpr/defaults.go
ext/typeexpr/defaults_test.go

This PR fixes the root cause of https://github.com/hashicorp/terraform/issues/32752.
Essentially, when the user passes in a type that cannot be converted into one assumed by the defaults package we would see a panic when attempting to retrieve the children of the mismatch type. For example, if we are attempting to convert a list into an object (which is not possible and what is happening in the original issue) then the defaults package would panic assuming an int type should be a string as that is what the index was expecting.
This PR makes that assumption safe by verifying both the expected type of the key and the cty type expected by the defaults package match. If they don't match, the defaults package will simply not apply the defaults (by returning `nil` from the getChild function, as …

Verify type assumptions when retrieving child default values

---

hclsyntax/expression_template.go
hclsyntax/expression_template_test.go

Fixes https://github.com/hashicorp/hcl/issues/616
There is no limit to the length of string prefixes produced by template expressions, so in rare cases they may return a refined unknown string has too long a prefix.
The `cty`'s msgpack decoder limits the size of an acceptable refinements to 1 kiB, so such a value cannot be handled and an error occurs.
This change limits the length of prefixes to 128 B, so overly long prefixes are no longer an issue in most cases.

hclsyntax: Impose an upper limit on a refined prefix in TemplateExpr

---

ext/tryfunc/tryfunc.go
ext/tryfunc/tryfunc_test.go

The `can` and `try` functions can return more precise results in some cases. Rather than try to inspect the expressions for any unknown values, rely on the evaluation result to be correct or error and base the decision on the evaluated values and errors.
A fundamental requirement for the `try` and `can` functions is that the value and types remain consistent as argument values are refined. This can be done provided we hold these conditions regarding unknowns to be true:
- An evaluation error can never be fixed by an unknown value becoming known.
- An entirely known value from an expression cannot later become unknown as values are refined.
- An expression result must always have a consistent type and value, only allowing the refinement of unknown values and types.
- An expression result …

Allow `can` and `try` functions to return known results with `unknown` values in the arguments

---

ext/typeexpr/defaults.go
ext/typeexpr/defaults_test.go

See also https://github.com/hashicorp/hcl/pull/590
See also https://github.com/terraform-linters/tflint/issues/1831
Refinements introduced in #590 has a restriction that it cannot refine unknown values of unknown types (`cty.DynamicVal`). Refining dynamic values causes a panic.
https://github.com/zclconf/go-cty/blob/v1.13.3/cty/unknown_refinement.go#L46-L47
The `typeexpr` extension may refine optional attribute as non-null, but dynamic values are not taken into account here, causing a panic.
This PR fixes the panic by avoiding refinement when the value type is `cty.DynamicPseudoType`. This is the same approach in the splat operator, so it's probably reasonable to do the same here.
https://github.com/hashicorp/hcl/blob/a9f8d65cae3cf64e58fc38f85c7970ab62964e8b/hclsyntax/expression.go#L1735-L …

ext/typeexpr: Avoid refinements on dynamic values

---

hcldec/spec_test.go

This test case is here to anticipate a _possible_ bug that isn't actually buggy in the current implementation: if an attribute spec is given a non-dynamic type constraint and then refined based on that type constraint then the hcldec implementation must perform the type conversion first and only then attempt to add the refinements.
Another possible variation here would be for the attribute spec to have a dynamic type constraint (`cty.DynamicPseudoType`) and then try to refine its result. That case isn't tested here because that's always an implementation error in the calling application: `RefineValueSpec` must be used only in ways that are valid for the full range of types that the nested spec could produce, and there are no refinements that are valid for the full range of …

hcldec: A test case for attributes set to cty.DynamicVal with refinements

---

ext/typeexpr/get_type.go
ext/typeexpr/get_type_test.go

This should fix https://github.com/hashicorp/terraform/issues/33757.

Check for duplicate keys in objects when building types from expressions

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Fixes https://github.com/hashicorp/hcl/issues/629 and transitively also https://github.com/opentofu/opentofu/issues/655 and https://github.com/hashicorp/terraform/issues/33977.
Solution inspired by other implementations in this very file, as well as primitive functions in the go-cty repository itself.

Fix conditionals erroring with an unknown condition and marked branch.

---

fuzz/oss_fuzz_build.sh

[google/oss-fuzz](https://github.com/google/oss-fuzz) runs continuous fuzzing on HCL, using a build script stored in the oss-fuzz repository. 
This PR (and https://github.com/google/oss-fuzz/pull/7907) will move the build script from https://github.com/google/oss-fuzz/blob/master/projects/hcl/build.sh into this repository, so we can maintain it more easily, as suggested by oss-fuzz maintainers.
oss-fuzz runs this script in a container, after cloning the HCL repository, to build a libFuzzer target from the HCL fuzzers.
Please note that this PR does not make the script work, which is the aim of the next PR.

fuzz: add oss-fuzz build script

---

hcldec/spec_test.go
hclsyntax/expression_test.go

In https://github.com/hashicorp/hcl/pull/630, and a couple other similar situations found while debugging that one, it became clear that interactions between refinements and marks are a bit of a hazard, since each involves a different kind of tag-along metadata that needs to be carefully preserved during evaluation.
That prompted me to go review the other refinements-related code added at the same time. I didn't yet find any specific bugs, but this PR includes some of the tests I added while I was reviewing, to help exercise more interactions between refinement and marks.
This doesn't change any non-test code.

hclsyntax, hcldec: Just some extra tests for marks and refinements interacting together

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Update cty to account for fixes in refinements.
When attempting to determine the final length range for a conditional expression with collections, the length values may still be unknown. Always use `Range()` to get the lower and upper bounds. Calls to `Range()` must also always be made with unmarked values.

hclsyntax: conditional refinements of collections must use Range()

---

hcldec/public_test.go
hcldec/spec.go

When hcldec needs to return a synthetic value, it must use WithoutOptionalAttributesDeep to ensure the correct type for Null or Unknown values. Optional attributes are normally removed from the value type when decoding, but since hcldec is dealing with the decoder spec directly, the optional attr types are still going to be present in these cases.

hcldec must use WithoutOptionalAttributesDeep

---

hclsyntax/expression.go
hclsyntax/expression_typeparams_test.go

Now that we have namespaced functions, and implementations like Terraform can add functions based on configuration, the reason for an unknown function call name becomes a little less clear. Because functions are populated outside of the hcl package scope, there isn't enough context to provide a useful diagnostic to the user.
We can create a new `Diagnostic.Extra` value satisfying a new `FunctionCallUnknownDiagExtra` interface, indicating specifically when a diagnostic is created due to an unknown function name. This will carry back the namespace and function name for the caller to inspect, which will allow refinement of the diagnostic based on information only known to the caller.

Create an error type for unknown function diags

---

hclwrite/format.go
hclwrite/format_test.go

```sh
echo 'attr = provider::framework::example()' | terraform fmt -
```
```hcl
attr = provider :: framework :: example()
```
```sh
echo 'attr = provider::framework::example()' | terraform fmt -
```
```hcl
attr = provider::framework::example()
```

hclwrite: Fix formatting of namespaced functions

---

.github/workflows/checks.yml

Previously we did not run unit tests on macOS. I don't know all the history but I will assume that was because the macOS runners were not available early on, or were otherwise difficult to use.
It seems relatively unlikely that there would be macOS-specific bugs we could discover that aren't more broadly Unix bugs (i.e. bugs that would be surfaced through Linux tests).
Regardless, the reality is that the products downstream of HCL, such as Terraform, do have macOS user base and we regularly run tests on macOS, so it would seem reasonable to also do it here.
While strictly speaking the version in `go.mod` is _compatibility constraint_, we always seem to test against that version, i.e. there is no difference in practice between the version we claim compatibility with and the version we test …

Run unit tests on macOS

---

Makefile
scripts/gofmtcheck.sh

This is to make it easier for existing and new maintainers and contributors to run checks on the codebase.
These targets can also run from CI which can be implemented as part of a separate PR.
```sh
make check
```
```
go run github.com/hashicorp/copywrite@latest headers --plan
Executing in dry-run mode. Rerun without the `--plan` flag to apply changes.
Using license identifier: MPL-2.0
Using copyright holder: HashiCorp, Inc.
Exempting the following search patterns:
hclsyntax/fuzz/testdata/**
hclwrite/fuzz/testdata/**
json/fuzz/testdata/**
specsuite/tests/**
The following files are missing headers:
go vet ./...
"/Users/radeksimko/gopath/src/github.com/hashicorp/hcl/scripts/gofmtcheck.sh"
```
```sh
make fix
```
```
go run github.com/hashicorp/copywrite@latest headers
Using license …
```

Add make targets for common checks + fixes

---

.github/workflows/checks.yml

This builds on top of https://github.com/hashicorp/hcl/pull/661
The aim with the Makefile was to ensure that developers/maintainers have the ability to run the same checks the same way as CI does. This PR tackles the CI part and delivers on that promise.

Use new make targets in CI

---

hclsyntax/parse_traversal_test.go
hclsyntax/parser_traversal.go
hclsyntax/public.go

This PR will eventually be used within Terraform to parse the "partial" addresses used by the deferred actions. We need support for the wildcards within traversals in order to reuse the larger logic for parsing traversals in general.
I've created a separate function for this so that this is a non-breaking change. For now, I haven't updated the behaviour of `SplatTraversal` so the automatic traversal functions will panic if called on a Traversal that contains the `[*]` index. We don't need this behaviour in Terraform (yet?) so I didn't want to introduce anything that couldn't be changed later.

Add additional function for parsing traversals with [*] keys

---

hclsyntax/expression.go
hclsyntax/expression_test.go

This fixes a panic for `example.*` if `example` is an unknown value that's marked.
We were calling `.Range()` on any unknown `sourceVal`, without first checking whether it was marked. That method panics if called on a marked value, so we need to strip that off first.
While testing this I found some return paths that weren't properly transferring the source value's marks to the output, and so this also addresses those so that all return paths preserve whatever markings are present on the source value.
In particular, if a non-list/set/tuple value gets "upgraded" into a tuple then we must transfer its marks onto the tuple, because the decision about constructing that value was based on characteristics of the source value.

hclsyntax: Don't panic if splat operand is unknown and marked

---

ext/dynblock/expand_body.go
ext/dynblock/expand_body_test.go
ext/dynblock/expand_spec.go
ext/dynblock/expr_wrap.go
ext/dynblock/unknown_body.go
go.mod
go.sum
hcldec/spec.go

Previously if the `for_each` expression was marked then expansion would fail because marked expressions are never directly iterable. (The failure also had a very confusing error message, because it wasn't directly testing whether the value was marked and was just assuming that any non-iterable value is non-iterable because it's of the wrong type.)
Now instead we'll allow marked for_each and preserve the marks into the values produced by the resulting block as much as we can.
This runs into the classic problem that HCL blocks are not values themselves and so cannot carry marks directly, but we can at least make sure that the values of any leaf arguments end up marked. We also ensure that applications that use `hcldec` (which includes Terraform) will see marks on the objects that represent …

ext/dynblock: Preserve marks from for_each expression into result

---

hclsyntax/parser.go
hclsyntax/parser_test.go

Return an `ExprSyntaxError` for invalid references that end in a dot (commonly occurs in editors for completions).
Detect value expressions of the `ExprSyntaxError` type when parsing object constructor expressions and use them to add an item to the result even though we skip parsing the object due to recovery after the invalid expression.
This allows the Terraform language server to support completions for object attributes after a dot was typed.

feat: return an `ExprSyntaxError` for invalid references that end in a dot

---

ops.go
ops_test.go

When traversing an unknown value or a `DynamicVal`, the marks from that initial value must be preserved for HCL Index and GetAttr operations. This mirrors the behavior of `GetAttr` and `Index` when used directly the underlying cty values.

Preserve marks when traversing unknown values

---

spec.md

Fixes a minor typo to rephrase the beginnign of the pragraph to:
"The _schema-driven_ processing model is useful when the expected structure of a body is known by the calling application."

docs: fix typo under "Dynamic Attributes Processing"

---

ext/dynblock/README.md

I'm studying HCL internals and when reading the docs for detecting variables in the `dynblock` package I got confused by the recursive function call but I noticed that for the depth-first, pre-order traversal the function name was wrong.
It's a small adjustment and I hope I can continue contributing more.
Thank you.

docs(ext/dynblock): recursive function call typo in detecting variables

---

decoder.go
decoder_test.go
hcl/parser/parser.go
hcl/parser/parser_test.go
parse.go
test-fixtures/basic_duplicates.hcl

- Added additional functions to replicate parsers old behavior to teams looking to switch aren't impacted by data that was already validated using the old parsers functionality. 
- Added additional test cases
- Cleaned up a segment of the duplicate code that was functionless

Add functions to replicate old HCL V1 Behavior for backwards compatability

---

hclsyntax/expression.go
hclsyntax/expression_template_test.go
hclsyntax/expression_test.go

The unknown value paths within conditional and for expressions were not consistently retaining marks.
In the case of for expressions, an unknown collection would lose all marks. If we have the any marks from the collection we can always return those. If the expression contains a conditional include, we can also attempt to obtain the marks from that since the conditional impacts the total collection value, the marks must alway be included in the final result. This gives us a more complete unknown value, but it can never contain a comprehensive set of marks for all cases. If the collection is entirely unknown, we have no idea what the element value marks are going to be though, so the final known result could still always include marks we were not anticipating.
The conditional expressions …

Better control of marks through conditional and for expressions

---

gohcl/decode.go
gohcl/decode_test.go
gohcl/doc.go
gohcl/schema.go

This PR updates the `gohcl` package so that users can automatically extra the source ranges for blocks and attributes using the following new tags:
- `def_range`
- `type_range`
- `label_range`
- `attr_range`
- `attr_name_range`
- `attr_value_range`
There's not breaking changes or backwards compatibility issues here, this is just all additive changes.

gohcl: allow gohcl to parse hcl.Range objects for blocks and attributes

---

hclsyntax/expression_ops.go
hclsyntax/expression_test.go

Taking inspiration from #538, this continues the effort to allow short-circuiting of boolean operators. I don't think we need to switch the operators to right-associative for short-circuiting to work like the previous PR, as I think the problem with the prior PR was that the decision to short-circuit requires both lhs and rhs values because short-circuiting happens in both directions for either operator. My guess was that the explicit switch to right-associative made some rhs short-circuits work, but it still doesn't work both ways. 
Given that HCL already evaluates boolean operations like so, it appears the associative-ness is OK:
```
> true || false && false
true
>  true || (false && false)
true
> (true || false) && false
false
```
and same with distributive identities with implied …

boolean operator short-circuiting

---

hclsyntax/expression.go
hclsyntax/expression_test.go

Unfortunately two of the weird splat rules we included to mimic Terraform v0.11's bizarre splat behavior interact in a broken way when combined using nested splat expressions:
1. Applying splat to a list or set value always returns a list value, rather than a tuple value, because that allows returning a more precise unknown value type when the source value is unknown.
2. Applying a splat to a scalar value returns a tuple of either zero or one elements, depending on whether the scalar is null. This returns a tuple rather than a list again because that allows returning more precise information in some unknown value cases.
When both of these rules are combined using a nested splat -- rule 2 inside rule 1 -- the second rule causes the nested results to have varying types based on the scalar …

hclsyntax: Detect and reject invalid nested splat result

---

hclsyntax/expression_ops.go
hclsyntax/expression_test.go

Follow up to #713.
A couple boolean expression tests were passing because diagnostics were accidentally dropped when there was no short-circuit return. Add a positive test for the diagnostics and make sure they are always collected from both sides of the expression.
The logic to drop diagnostics needed to be within the short-circuit implementations, where a good LHS unknown value (one without any errors) prevents further evaluation allowing us to optimistically skip the RHS diagnostics. This can be confusing, because the logic looked correct, but we need to remember that cty/hcl return an unknown value when faced with errors too, and part of the short-circuit logic is to selectively handle errors when possible.

fix boolean short-circuit diagnostic handling

---

hclwrite/ast_attribute.go
hclwrite/ast_body.go
hclwrite/ast_body_test.go

Adding the ability to change the name of an attribute already set on a block body. This can be used to automate renaming of terraform `locals`.
Without this, the only obvious approach is to remove the current attribute and add a new one, but this loses the order and comments which isn't desirable.
```
attr := block.Body().GetAttribute(fromName)
if attr != nil {
attr.SetName(toName)
}
```
*UPDATE*
```
wasChanged := block.Body().RenameAttribute(fromName, toName)
```

hclwrite: Add RenameAttribute on Body

---

.github/workflows/checks.yml

- I have added unit test coverage in the go-multierror.yml workflow
- The unit test coverage change was done to help understand the defects early in lifecycle and come up with a good solution for it.

Coverage test

---

decoder.go
decoder_test.go
hcl/parser/parser.go
hcl/parser/parser_test.go
parse.go
test-fixtures/basic_duplicates.hcl

For reasons of backwards compatibility, Nomad uses an older branch of HCL1 ([`v1.0.1-nomad`](https://github.com/hashicorp/hcl/tree/v1.0.1-nomad)) and HCL2 ([`v2.20.2-nomad-1`](https://github.com/hashicorp/hcl/tree/v2.20.2-nomad-1)), and backports a limited set of changes to those branches. 
But the Vault API also has their own HCL1 branch, currently tagged as [`v1.0.1-vault-7`](https://github.com/hashicorp/hcl/tree/v1.0.1-vault-7). Normally this isn't a problem because Nomad pins to our own branch and we don't call any of the Vault API package's HCL code anyways. But in https://github.com/hashicorp/hcl/pull/707 some functions were changed that break our build (ref https://github.com/hashicorp/nomad/pull/26006) unless we backport them.
This PR cherry-picks the Vault HCL1 changes to the …

cherry-pick Vault changes to Nomad HCL1 branch
